# fly.toml app configuration file generated for juanapposa3 on 2023-09-12T15:28:35+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "juanapposa3"
primary_region = "ams"

[build]

[env]
PORT = "3001"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
