# fly.toml app configuration file generated for twilight-surf-5134 on 2023-09-16T17:03:51+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "twilight-surf-5134"
primary_region = "ams"

[build]

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
